In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Define path to csv for crime suburb file
crime_DF_final = "01_Outputs/crime_DF.csv"

In [3]:
#Read in and create dataframe for crime data clean up
crimefinal = pd.read_csv(crime_DF_final)
crimefinal

,Local Government Area,postcode,suburb,crime_id,crime_name,average_incdent
0,Banyule,3079,ivanhoe,A20,Assault and related offences,43.600000
1,Banyule,3079,ivanhoe,A50,Robbery,3.000000
2,Banyule,3079,ivanhoe,A70,"Stalking, harassment and threatening behaviour",8.100000
3,Banyule,3079,ivanhoe,A80,Dangerous and negligent acts endangering people,3.333333
4,Banyule,3079,ivanhoe,B10,Arson,3.400000
...,...,...,...,...,...,...
7512,Yarra Ranges,3796,mount evelyn,D30,Public nuisance offences,1.833333
7513,Yarra Ranges,3796,mount evelyn,E10,Justice procedures,4.250000
7514,Yarra Ranges,3796,mount evelyn,E20,Breaches of orders,21.800000
7515,Yarra Ranges,3796,mount evelyn,F90,Miscellaneous offences,4.333333
7516,Yarra Ranges,3796,mount evelyn,Other,crimes against the person,10.300000

In [4]:
#Check data info for null fields - Total records are 9890
crimefinal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7517 entries, 0 to 7516
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Local Government Area  7517 non-null   object
 1   postcode               7517 non-null   int64
 2   suburb                 7517 non-null   object
 3   crime_id               7517 non-null   object
 4   crime_name             7517 non-null   object
 5   average_incdent        7517 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 352.5+ KB

In [5]:
#To look for duplications, misspelling, leading spaces etc - check unique values for following columns:
#Local Government Area, postcode, suburb, crime_id, crime_name
crimeuniqueLGA = crimefinal["Local Government Area"].unique()
crimeuniqueLGA.sort()
print(crimeuniqueLGA)
len(crimeuniqueLGA)

['Banyule' 'Bayside' 'Boroondara' 'Brimbank' 'Cardinia' 'Casey' 'Darebin'
 'East Gippsland' 'Frankston' 'Glen Eira' 'Greater Dandenong'
 'Hobsons Bay' 'Hume' 'Kingston' 'Knox' 'Manningham' 'Maribyrnong'
 'Maroondah' 'Melbourne' 'Melton' 'Monash' 'Moonee Valley' 'Moreland'
 'Nillumbik' 'Northern Grampians' 'Port Phillip' 'Stonnington'
 'Whitehorse' 'Whittlesea' 'Wyndham' 'Yarra' 'Yarra Ranges']

32

In [6]:
#postcode
crimeuniquepostcode = crimefinal["postcode"].unique()
crimeuniquepostcode.sort()
print(crimeuniquepostcode)
len(crimeuniquepostcode)

[3000 3002 3003 3004 3005 3006 3008 3010 3011 3012 3013 3015 3016 3018
 3020 3021 3022 3023 3025 3028 3029 3030 3031 3032 3033 3034 3036 3037
 3038 3039 3040 3041 3042 3043 3044 3046 3047 3048 3049 3050 3051 3052
 3053 3054 3055 3056 3057 3058 3060 3061 3064 3065 3066 3067 3068 3070
 3071 3072 3073 3074 3075 3076 3078 3079 3081 3082 3083 3084 3085 3086
 3087 3088 3089 3093 3094 3095 3099 3101 3102 3103 3104 3105 3106 3107
 3108 3109 3111 3113 3114 3121 3122 3123 3124 3125 3126 3127 3128 3129
 3130 3131 3132 3133 3134 3135 3136 3137 3138 3139 3140 3141 3142 3143
 3144 3145 3146 3147 3148 3149 3150 3151 3152 3153 3154 3155 3156 3158
 3159 3160 3161 3162 3163 3165 3166 3167 3168 3169 3170 3171 3172 3173
 3174 3175 3177 3178 3179 3180 3181 3182 3183 3184 3185 3186 3187 3188
 3189 3190 3191 3192 3193 3194 3195 3196 3197 3198 3199 3200 3201 3202
 3204 3205 3206 3207 3381 3752 3765 3766 3767 3782 3786 3787 3789 3791
 3792 3796 3800 3802 3803 3804 3805 3806 3875 3910 3911 3975 3976 3977]

196

In [7]:
#suburb
crimeuniquesuburb = crimefinal["suburb"].unique()
crimeuniquesuburb.sort()
print(crimeuniquesuburb)
len(crimeuniquesuburb)

['abbotsford' 'aberfeldie' 'airport west' 'albanvale' 'albert park'
 'albion' 'alphington' 'altona' 'altona meadows' 'altona north' 'ardeer'
 'armadale' 'ascot vale' 'ashburton' 'ashwood' 'aspendale'
 'aspendale gardens' 'attwood' 'avondale heights' 'balaclava' 'balwyn'
 'balwyn north' 'bangholme' 'bayswater' 'bayswater north' 'beaumaris'
 'belgrave' 'belgrave heights' 'bellfield' 'bentleigh' 'bentleigh east'
 'berwick' 'black rock' 'blackburn' 'blackburn north' 'blackburn south'
 'bonbeach' 'boronia' 'box hill' 'box hill north' 'box hill south'
 'briar hill' 'brighton' 'brighton east' 'broadmeadows' 'brooklyn'
 'brunswick' 'brunswick east' 'brunswick west' 'bulleen' 'bundoora'
 'burnley' 'burnside' 'burnside heights' 'burwood' 'burwood east'
 'cairnlea' 'camberwell' 'campbellfield' 'canterbury' 'carlton'
 'carlton north' 'carnegie' 'caroline springs' 'carrum' 'carrum downs'
 'caulfield' 'caulfield east' 'caulfield north' 'caulfield south'
 'chadstone' 'chelsea' 'chelsea heights' 'cheltenham' 'clarinda' 'clayton'
 'clayton south' 'clematis' 'clifton hill' 'coburg' 'coburg north'
 'collingwood' 'coolaroo' 'craigieburn' 'cranbourne' 'cranbourne north'
 'cremorne' 'croydon' 'croydon hills' 'croydon north' 'croydon south'
 'dallas' 'dandenong' 'dandenong north' 'dandenong south' 'deer park'
 'delahey' 'derrimut' 'diamond creek' 'dingley village' 'docklands'
 'doncaster' 'doncaster east' 'donvale' 'doveton' 'eaglemont'
 'east melbourne' 'edithvale' 'elsternwick' 'eltham' 'eltham north'
 'elwood' 'emerald' 'endeavour hills' 'epping' 'essendon' 'essendon north'
 'essendon west' 'eumemmerring' 'fairfield' 'fawkner' 'ferntree gully'
 'ferny creek' 'fitzroy' 'fitzroy north' 'flemington' 'footscray'
 'forest hill' 'frankston' 'frankston north' 'frankston south'
 'gardenvale' 'gladstone park' 'glen huntly' 'glen iris' 'glen waverley'
 'glenroy' 'gowanbrae' 'greensborough' 'hadfield' 'hallam' 'hampton east'
 'hampton park' 'hawthorn' 'hawthorn east' 'heatherton' 'heathmont'
 'heidelberg' 'heidelberg heights' 'heidelberg west' 'highett' 'hillside'
 'hoppers crossing' 'hughesdale' 'huntingdale' 'hurstbridge' 'ivanhoe'
 'ivanhoe east' 'jacana' 'junction village' 'kallista' 'kalorama' 'kealba'
 'keilor' 'keilor downs' 'keilor east' 'keilor lodge' 'keilor park'
 'kensington' 'kew' 'kew east' 'keysborough' 'kilsyth' 'kilsyth south'
 'kings park' 'kingsbury' 'kingsville' 'knoxfield' 'kooyong' 'lalor'
 'langwarrin' 'langwarrin south' 'laverton' 'lilydale' 'lower plenty'
 'lynbrook' 'lyndhurst' 'lysterfield south' 'macleod' 'maidstone'
 'malvern' 'malvern east' 'maribyrnong' 'mckinnon' 'meadow heights'
 'melbourne' 'mentone' 'middle park' 'mill park' 'mitcham' 'mont albert'
 'mont albert north' 'montmorency' 'montrose' 'moonee ponds' 'moorabbin'
 'mooroolbark' 'mordialloc' 'mount dandenong' 'mount evelyn'
 'mount waverley' 'mulgrave' 'murrumbeena' 'narre warren'
 'narre warren north' 'narre warren south' 'newport' 'niddrie'
 'noble park' 'noble park north' 'north melbourne' 'north warrandyte'
 'northcote' 'notting hill' 'nunawading' 'oak park' 'oakleigh'
 'oakleigh east' 'oakleigh south' 'ormond' 'park orchards' 'parkdale'
 'parkville' 'pascoe vale' 'pascoe vale south' 'patterson lakes'
 'point cook' 'port melbourne' 'prahran' 'preston' 'princes hill'
 'research' 'reservoir' 'richmond' 'ringwood' 'ringwood north' 'ripponlea'
 'rosanna' 'rowville' 'roxburgh park' 'sandhurst' 'sandringham'
 'sassafras' 'scoresby' 'seabrook' 'seaford' 'seaholme' 'seddon' 'selby'
 'sherbrooke' 'skye' 'south kingsville' 'south melbourne' 'south morang'
 'south yarra' 'southbank' 'spotswood' 'springvale' 'springvale south'
 'st albans' 'st kilda' 'st kilda east' 'st kilda west' 'strathmore'
 'strathmore heights' 'sunshine north' 'surrey hills' 'sydenham'
 'taylors hill' 'taylors lakes' 'tecoma' 'templestowe' 'templestowe lower'
 'the basin' 'the patch' 'thomastown' 'thornbury' 'toorak' 'travancore'
 'tullamarine' 'upper ferntree gully' 'upwey' 'vermont' 'vermont south'
 'viewbank' 'wandin north' 'wantirna' 'wantirna south' 'warrandyte'
 'warranwood' 'waterways' 'watsonia' 'watsonia north' 'werribee'
 'west footscray' 'west melbourne' 'westmeadows' 'wheelers hill'
 'williamstown' 'williamstown north' 'windsor' 'yallambie' 'yarraville']

313

In [8]:
#crime_id
crimeuniquecrime_id = crimefinal["crime_id"].unique()
crimeuniquecrime_id.sort()
print(crimeuniquecrime_id)
len(crimeuniquecrime_id)

#Other is ok as field in PostgreSql is VARCHAR(5)

['A20' 'A50' 'A70' 'A80' 'B10' 'B20' 'B30' 'B40' 'B50' 'B60' 'C10' 'C20'
 'C30' 'C90' 'D10' 'D20' 'D30' 'D40' 'E10' 'E20' 'F10' 'F20' 'F30' 'F90'
 'Other']

25

In [9]:
#crime_name
crimeuniquecrime_name = crimefinal["crime_name"].unique()
crimeuniquecrime_name.sort()
print(crimeuniquecrime_name)
len(crimeuniquecrime_name)

['Arson' 'Assault and related offences' 'Breaches of orders' 'Bribery'
 'Burglary/Break and enter' 'Cultivate or manufacture drugs'
 'Dangerous and negligent acts endangering people' 'Deception'
 'Disorderly and offensive conduct' 'Drug dealing and trafficking'
 'Drug use and possession' 'Justice procedures' 'Miscellaneous offences'
 'Other drug offences' 'Other government regulatory offences'
 'Property damage' 'Public nuisance offences' 'Public security offences'
 'Regulatory driving offences' 'Robbery'
 'Stalking, harassment and threatening behaviour' 'Theft'
 'Transport regulation offences' 'Weapons and explosives offences'
 'crimes against the person']

25

In [10]:
#strip leading and trailing space - no indication of leading spaces - no action required

In [11]:
#Canonicalize/standardize values and column headers if needed
#Match DF columns with final table schema
#Currene columns=
crimefinal.columns

Index(['Local Government Area', 'postcode', 'suburb', 'crime_id', 'crime_name',
       'average_incdent'],
      dtype='object')

In [12]:
#rename columns 
suburb_vs_crime = crimefinal.rename(columns={'Local Government Area':'lga_name', 'average_incdent':'average_incident'})
suburb_vs_crime

,lga_name,postcode,suburb,crime_id,crime_name,average_incident
0,Banyule,3079,ivanhoe,A20,Assault and related offences,43.600000
1,Banyule,3079,ivanhoe,A50,Robbery,3.000000
2,Banyule,3079,ivanhoe,A70,"Stalking, harassment and threatening behaviour",8.100000
3,Banyule,3079,ivanhoe,A80,Dangerous and negligent acts endangering people,3.333333
4,Banyule,3079,ivanhoe,B10,Arson,3.400000
...,...,...,...,...,...,...
7512,Yarra Ranges,3796,mount evelyn,D30,Public nuisance offences,1.833333
7513,Yarra Ranges,3796,mount evelyn,E10,Justice procedures,4.250000
7514,Yarra Ranges,3796,mount evelyn,E20,Breaches of orders,21.800000
7515,Yarra Ranges,3796,mount evelyn,F90,Miscellaneous offences,4.333333
7516,Yarra Ranges,3796,mount evelyn,Other,crimes against the person,10.300000

### Exporting suburb_vs_crime csv

In [13]:
#Export to CSV with final table schema file name
suburb_vs_crime.to_csv('01_Outputs/suburbCrimeDataClean.csv', index=False)

suburb_vs_crime.to_csv('../005_Load_SQL/01_Inputs/suburb_vs_crime.csv', index=False)

#####THIS IS THE END OF WHAT I HAVE RUN FOR 02/03/2021
#####I THINK SOME ONE ELSE DID THE REST OF THE CODING?
####NEED TO CHECK THAT THIS CAN BE RUN
####IF USING DATAFRAME suburb_vs_crime ABOVE BEED TO USE NEW ONE FROM Crime - Transformation 3 notebook

### Creating crime_types csv

In [14]:
crime_type = suburb_vs_crime.groupby(['crime_id','crime_name'])['average_incident'].sum()

In [15]:
crime_type = pd.DataFrame(crime_type)

In [16]:
crime_type = crime_type.reset_index()

In [17]:
crime_type = crime_type[['crime_id','crime_name']]

In [18]:
crime_type.to_csv('../005_Load_SQL/01_Inputs/crime_type.csv', index = False)

### Creating place_type_vs_crime csv

In [19]:
places_types = pd.read_csv('../005_Load_SQL/01_Inputs/places_types.csv')

suburbs_postcode_lat_lon = pd.read_csv('../005_Load_SQL/01_Inputs/suburbs_postcode_lat_lon.csv')

suburb_vs_places_type = pd.read_csv('../005_Load_SQL/01_Inputs/suburb_vs_places_type.csv')

crime_type = crime_type

suburb_vs_crime = suburb_vs_crime

In [20]:
a1 = places_types.merge(suburb_vs_places_type, on='place_id', how = 'inner')

In [21]:
a2 = a1.merge(suburbs_postcode_lat_lon, on = 'suburb', how='inner')

In [22]:
a3 = a2.merge(suburb_vs_crime, on='suburb', how = 'inner')

In [23]:
a3.merge(crime_type, on ='crime_id', how = 'inner')

,place_id,place_type,suburb,place_type_count,postcode_x,lat,lon,lga_name,postcode_y,crime_id,crime_name_x,average_incident,crime_name_y
0,0,liquor_store,abbotsford,15.0,3067,-37.801781,144.998752,Yarra,3067,A20,Assault and related offences,56.0,Assault and related offences
1,1,police,abbotsford,1.0,3067,-37.801781,144.998752,Yarra,3067,A20,Assault and related offences,56.0,Assault and related offences
2,2,park,abbotsford,20.0,3067,-37.801781,144.998752,Yarra,3067,A20,Assault and related offences,56.0,Assault and related offences
3,0,liquor_store,aberfeldie,1.0,3040,-37.756690,144.896259,Moonee Valley,3040,A20,Assault and related offences,8.6,Assault and related offences
4,1,police,aberfeldie,0.0,3040,-37.756690,144.896259,Moonee Valley,3040,A20,Assault and related offences,8.6,Assault and related offences
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22960,1,police,williamstown,0.0,3016,-37.856902,144.897698,Hobsons Bay,3016,D40,Public security offences,1.0,Public security offences
22961,2,park,williamstown,18.0,3016,-37.856902,144.897698,Hobsons Bay,3016,D40,Public security offences,1.0,Public security offences
22962,0,liquor_store,windsor,17.0,3181,-37.856159,144.992200,Stonnington,3181,D40,Public security offences,1.0,Public security offences
22963,1,police,windsor,0.0,3181,-37.856159,144.992200,Stonnington,3181,D40,Public security offences,1.0,Public security offences
22964,2,park,windsor,20.0,3181,-37.856159,144.992200,Stonnington,3181,D40,Public security offences,1.0,Public security offences

In [24]:
place_type_vs_crime = a3[['place_id','crime_id','average_incident']]

In [25]:
place_type_vs_crime.to_csv('../005_Load_SQL/01_Inputs/place_type_vs_crime.csv')